Feature/detection rebase
aindustriosa/RatibroombroomSW pull request #17
Opened 2020-12-12 16:32 UTC by hmightypirate

2020-12-12 16:59 UTC, eLeDe commented on src/hal/setup.c
> +  nvic_set_priority(NVIC_TIM1_UP_TIM10_IRQ, 0);
We must set here all interruptions priorities

2020-12-12 17:10 UTC, eLeDe requested changes
Set interruption priorities to all enabled IRQs

2020-12-12 17:31 UTC, hmightypirate commented
Done

2020-12-12 18:51 UTC, eLeDe approved these changes
:ok_hand:

2020-12-13 18:09 UTC, punkto commented
:ok:

2020-12-19 16:37 UTC, hmightypirate commented
Removing this pull because the conflict was resolved in another pull

2020-12-19 16:37 UTC, closed without merging