Feature/eeprom
aindustriosa/RatibroombroomSW pull request #21
Opened 2020-12-19 18:08 UTC by hmightypirate

2020-12-19 19:57 UTC, eLeDe commented on src/hal/eeprom.c
>  uint32_t eeprom_erase_page(uint32_t page_address)
Rename to eeprom_erase_sectors()

2020-12-19 19:58 UTC, eLeDe requested changes
Rename and deprecate function eeprom_erase_page()

2020-12-19 20:55 UTC, punkto approved these changes

2020-12-26 15:51 UTC, merged

2020-12-27 16:27 UTC, eLeDe reviewed
:ok: